services:
  postgres:
    image: postgres:15
    container_name: postgres-demo-blog-db
    environment:
      POSTGRES_DB: demo_blog
      POSTGRES_USER: demo_blog
      POSTGRES_PASSWORD: demo_blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo_blog -d demo_blog" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: demo-blog-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: 'True'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
